@if($errors->any())<div role="alert" class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{{ __('Please correct the highlighted fields.') }}</div>@endif
<form method="POST" action="{{ route('admin.donations.store') }}" class="grid gap-5 sm:grid-cols-2" x-data="{ anonymous: {{ old('is_anonymous') ? 'true' : 'false' }} }">@csrf
    <label class="block"><span class="text-sm font-medium">{{ __('Mosque') }}</span><select required name="mosque_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">{{ __('Choose mosque') }}</option>@foreach($mosques as $mosque)<option value="{{ $mosque->id }}" @selected(old('mosque_id')==$mosque->id)>{{ $mosque->name }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm font-medium">{{ __('Contribution type') }}</span><select required name="contribution_type" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['donation','offering','subscription','subsidy','other'] as $type)<option value="{{ $type }}" @selected(old('contribution_type')===$type)>{{ __($type) }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm font-medium">{{ __('Amount') }}</span><input required name="amount" inputmode="decimal" value="{{ old('amount') }}" class="mt-1 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">{{ __('Currency') }}</span><select name="currency" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['GNF','USD','EUR'] as $currency)<option value="{{ $currency }}" @selected(old('currency','GNF')===$currency)>{{ $currency }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm font-medium">{{ __('Payment method') }}</span><select required name="payment_method" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['cash','bank_transfer','mobile_money','cheque','card','other'] as $method)<option value="{{ $method }}" @selected(old('payment_method')===$method)>{{ __($method) }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm font-medium">{{ __('Received at') }}</span><input required type="datetime-local" name="received_at" value="{{ old('received_at',now()->format('Y-m-d\TH:i')) }}" class="mt-1 w-full rounded-xl border-slate-300"></label>
    <label class="flex items-center gap-3 sm:col-span-2"><input type="checkbox" name="is_anonymous" value="1" x-model="anonymous" class="rounded border-slate-300"><span>{{ __('Anonymous contribution') }}</span></label>
    <label class="block" x-show="!anonymous"><span class="text-sm font-medium">{{ __('Faithful record') }}</span><select name="faithful_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">{{ __('None') }}</option>@foreach($faithful as $record)<option value="{{ $record->id }}" @selected(old('faithful_id')==$record->id)>{{ $record->registration_number }} — {{ $record->first_name }} {{ $record->last_name }}</option>@endforeach</select></label>
    <label class="block" x-show="!anonymous"><span class="text-sm font-medium">{{ __('Donor name') }}</span><input name="donor_name" value="{{ old('donor_name') }}" class="mt-1 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">{{ __('Payment reference') }}</span><input name="payment_reference" value="{{ old('payment_reference') }}" class="mt-1 w-full rounded-xl border-slate-300"></label>
    <label class="block sm:col-span-2"><span class="text-sm font-medium">{{ __('Notes') }}</span><textarea name="notes" rows="3" class="mt-1 w-full rounded-xl border-slate-300">{{ old('notes') }}</textarea></label>
    <div class="flex gap-3 sm:col-span-2"><button class="rounded-xl bg-emerald-600 px-5 py-2.5 font-semibold text-white">{{ __('Save') }}</button><a href="{{ route('admin.donations.index') }}" class="rounded-xl border px-5 py-2.5">{{ __('Cancel') }}</a></div>
</form>
