<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-4"><div><h1 class="text-lg font-bold">{{ __('Mosques') }}</h1><p class="text-xs text-slate-500">{{ __('Manage mosques within your authorized scope.') }}</p></div>@can('mosques.create')<a href="{{ route('admin.mosques.create') }}" class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-600 focus:ring-offset-2">{{ __('Add mosque') }}</a>@endcan</div></x-slot>
    <div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        @if ($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">{{ __('The filters could not be applied.') }}</div>@endif
        <section class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5" aria-labelledby="filters-heading">
            <h2 id="filters-heading" class="font-semibold">{{ __('Search and filters') }}</h2>
            <form method="GET" action="{{ route('admin.mosques.index') }}" class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" x-data="{ loading: false }" @submit="loading = true">
                <label class="lg:col-span-2"><span class="text-sm font-medium text-slate-700">{{ __('Search') }}</span><input name="search" value="{{ $filters['search'] ?? '' }}" maxlength="100" placeholder="{{ __('Name or code') }}" class="mt-1 block w-full rounded-xl border-slate-300 focus:border-emerald-500 focus:ring-emerald-500"></label>
                <label><span class="text-sm font-medium text-slate-700">{{ __('Status') }}</span><select name="status" class="mt-1 block w-full rounded-xl border-slate-300 focus:border-emerald-500 focus:ring-emerald-500"><option value="">{{ __('All statuses') }}</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>{{ __('active') }}</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>{{ __('inactive') }}</option></select></label>
                <label><span class="text-sm font-medium text-slate-700">{{ __('Region') }}</span><select name="region" class="mt-1 block w-full rounded-xl border-slate-300 focus:border-emerald-500 focus:ring-emerald-500"><option value="">{{ __('All regions') }}</option>@foreach($regions as $region)<option value="{{ $region }}" @selected(($filters['region'] ?? '') === $region)>{{ $region }}</option>@endforeach</select></label>
                <div class="flex gap-2 sm:col-span-2 lg:col-span-4"><button :disabled="loading" class="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"><span x-show="!loading">{{ __('Apply filters') }}</span><span x-cloak x-show="loading">{{ __('Loading…') }}</span></button><a href="{{ route('admin.mosques.index') }}" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ __('Reset') }}</a></div>
            </form>
        </section>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" aria-labelledby="results-heading">
            <div class="border-b border-slate-100 px-5 py-4"><h2 id="results-heading" class="font-bold">{{ trans_choice(':count mosque|:count mosques', $mosques->total(), ['count' => $mosques->total()]) }}</h2></div>
            @if($mosques->isEmpty())<div class="px-6 py-14 text-center"><p class="font-semibold text-slate-700">{{ __('No mosques match these filters.') }}</p><p class="mt-1 text-sm text-slate-500">{{ __('Adjust or reset the filters to continue.') }}</p></div>
            @else
                <div class="hidden overflow-x-auto md:block"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr>@foreach([__('Mosque'),__('Location'),__('Administrator'),__('Status'),__('Actions')] as $heading)<th class="px-5 py-3 text-start text-xs font-semibold uppercase tracking-wider text-slate-500">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@foreach($mosques as $mosque)<tr class="hover:bg-slate-50"><td class="px-5 py-4"><a class="font-semibold text-emerald-700 hover:text-emerald-600" href="{{ route('admin.mosques.show', $mosque) }}">{{ $mosque->name }}</a><p class="text-xs text-slate-500">{{ $mosque->code }}</p></td><td class="px-5 py-4 text-sm text-slate-600">{{ $mosque->commune }}, {{ $mosque->region }}</td><td class="px-5 py-4 text-sm text-slate-600">{{ $mosque->administrator?->name ?? __('Not assigned') }}</td><td class="px-5 py-4"><x-mosque-status-badge :status="$mosque->status" /></td><td class="px-5 py-4"><a href="{{ route('admin.mosques.show', $mosque) }}" class="text-sm font-semibold text-emerald-700">{{ __('View details') }}</a></td></tr>@endforeach</tbody></table></div>
                <div class="divide-y divide-slate-100 md:hidden">@foreach($mosques as $mosque)<article class="p-5"><div class="flex items-start justify-between gap-3"><div><a class="font-bold text-emerald-700" href="{{ route('admin.mosques.show', $mosque) }}">{{ $mosque->name }}</a><p class="text-xs text-slate-500">{{ $mosque->code }}</p></div><x-mosque-status-badge :status="$mosque->status" /></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-xs text-slate-500">{{ __('Location') }}</dt><dd>{{ $mosque->commune }}, {{ $mosque->region }}</dd></div><div><dt class="text-xs text-slate-500">{{ __('Administrator') }}</dt><dd>{{ $mosque->administrator?->name ?? __('Not assigned') }}</dd></div></dl><a href="{{ route('admin.mosques.show', $mosque) }}" class="mt-4 inline-flex text-sm font-semibold text-emerald-700">{{ __('View details') }}</a></article>@endforeach</div>
                @if($mosques->hasPages())<div class="border-t border-slate-100 px-5 py-4">{{ $mosques->links() }}</div>@endif
            @endif
        </section>
    </div>
</x-app-layout>
