@php($editing = isset($faithful))
<form method="POST" action="{{ $editing ? route('admin.faithful.update',$faithful) : route('admin.faithful.store') }}" class="space-y-6" x-data="{submitting:false}" @submit="submitting=true">@csrf @if($editing)@method('PATCH')@endif
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">{{ __('Please correct the highlighted fields.') }}</div>@endif
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-bold">{{ __('Identity and membership') }}</h2><div class="mt-5 grid gap-4 sm:grid-cols-2">
<label><span class="text-sm font-semibold">{{ __('Mosque') }}</span><select required name="mosque_id" class="mt-1 w-full rounded-xl border-slate-300">@foreach($mosques as $mosque)<option value="{{ $mosque->id }}" @selected(old('mosque_id',$faithful->mosque_id ?? '')==$mosque->id)>{{ $mosque->name }}</option>@endforeach</select>@error('mosque_id')<small class="text-red-600">{{ $message }}</small>@enderror</label>
@foreach([['registration_number',__('Registration number'),'text'],['first_name',__('First name'),'text'],['last_name',__('Last name'),'text'],['birth_date',__('Birth date'),'date'],['joined_at',__('Joined at'),'date']] as [$name,$label,$type])<label><span class="text-sm font-semibold">{{ $label }}</span><input type="{{ $type }}" name="{{ $name }}" value="{{ old($name,isset($faithful) && $faithful->{$name} ? ($faithful->{$name} instanceof Carbon\CarbonInterface ? $faithful->{$name}->toDateString() : $faithful->{$name}) : ($name==='joined_at' ? now()->toDateString() : '')) }}" @required(in_array($name,['registration_number','first_name','last_name','joined_at'])) class="mt-1 w-full rounded-xl border-slate-300">@error($name)<small class="text-red-600">{{ $message }}</small>@enderror</label>@endforeach
<label><span class="text-sm font-semibold">{{ __('Gender') }}</span><select name="gender" class="mt-1 w-full rounded-xl border-slate-300"><option value="">{{ __('Not specified') }}</option>@foreach(['male','female','other'] as $value)<option value="{{ $value }}" @selected(old('gender',$faithful->gender ?? '')===$value)>{{ __($value) }}</option>@endforeach</select></label><label><span class="text-sm font-semibold">{{ __('Status') }}</span><select name="status" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['active','inactive','suspended','deceased'] as $value)<option value="{{ $value }}" @selected(old('status',$faithful->status ?? 'active')===$value)>{{ __($value) }}</option>@endforeach</select></label></div></section>
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-bold">{{ __('Private contact information') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('Use this information only for authorized community administration.') }}</p><div class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['phone',__('Phone'),'text'],['email',__('Email'),'email'],['occupation',__('Occupation'),'text'],['emergency_contact_name',__('Emergency contact name'),'text'],['emergency_contact_phone',__('Emergency contact phone'),'text']] as [$name,$label,$type])<label><span class="text-sm font-semibold">{{ $label }}</span><input type="{{ $type }}" name="{{ $name }}" value="{{ old($name,$faithful->{$name} ?? '') }}" class="mt-1 w-full rounded-xl border-slate-300">@error($name)<small class="text-red-600">{{ $message }}</small>@enderror</label>@endforeach<label class="sm:col-span-2"><span class="text-sm font-semibold">{{ __('Address') }}</span><textarea name="address" class="mt-1 w-full rounded-xl border-slate-300">{{ old('address',$faithful->address ?? '') }}</textarea></label><label class="sm:col-span-2"><span class="text-sm font-semibold">{{ __('Notes') }}</span><textarea name="notes" rows="4" class="mt-1 w-full rounded-xl border-slate-300">{{ old('notes',$faithful->notes ?? '') }}</textarea></label></div></section>
<section class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><label class="flex gap-3"><input type="checkbox" required class="mt-1 rounded border-slate-300 text-emerald-600" @checked($editing || old('consent_at')) onchange="this.form.consent_at.value=this.checked?new Date().toISOString():''"><span><strong>{{ __('Consent recorded') }}</strong><span class="block text-sm text-slate-600">{{ __('Confirm that consent to store these personal details has been obtained.') }}</span></span></label><input type="hidden" name="consent_at" value="{{ old('consent_at',isset($faithful) && $faithful->consent_at ? $faithful->consent_at->toIso8601String() : now()->toIso8601String()) }}"></section>
<div class="flex justify-end gap-3"><a href="{{ $editing ? route('admin.faithful.show',$faithful) : route('admin.faithful.index') }}" class="rounded-xl border px-5 py-3 text-sm font-semibold">{{ __('Cancel') }}</a><button :disabled="submitting" class="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">{{ __('Save') }}</button></div></form>
